---
- hosts: prometheus
  become: true
  vars:
    packages:
      download_url: https://github.com/prometheus/prometheus/releases/download/v2.48.0/prometheus-2.48.0.linux-amd64.tar.gz
      package_name: prometheus-2.48.0.linux-amd64.tar.gz
    temp_dir: /tmp
    config_dir: /etc/prometheus
    data_dir: /var/lib/prometheus
    hosts_file_path: /etc/hosts

  tasks:
    - name: Add entries to /etc/hosts
      blockinfile:
        path: "{{ hosts_file_path }}"
        block: |
          # The following lines are using for KES Server
          192.168.9.108 server-1
          192.168.9.112 server-2
          192.168.9.113 server-3

    - name: Download Prometheus v2.48.0
      get_url:
        url: "{{ packages.download_url }}"
        dest: "{{ temp_dir }}/{{ packages.package_name }}"

    - name: Extract Prometheus v2.48.0
      ansible.builtin.unarchive:
        src: "{{ temp_dir }}/{{ packages.package_name }}"
        dest: "{{ temp_dir }}"
        remote_src: yes

    - name: Create prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present

    - name: Create prometheus user
      ansible.builtin.user:
        name: prometheus
        group: prometheus
        shell: /sbin/nologin
        system: yes
        createhome: no

    - name: Create Config and Data Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ config_dir }}"
        - "{{ data_dir }}"

    - name: Copy Prometheus Binary Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        owner: root
        mode: "0755"
        group: root
        remote_src: yes
      with_items:
        - "{{ temp_dir }}/prometheus-2.48.0.linux-amd64/prometheus"
        - "{{ temp_dir }}/prometheus-2.48.0.linux-amd64/promtool"

    - name: Copy Prometheus Files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ config_dir }}"
        owner: root
        group: root
        remote_src: yes
      with_items:
        - "{{ temp_dir }}/prometheus-2.48.0.linux-amd64/consoles"
        - "{{ temp_dir }}/prometheus-2.48.0.linux-amd64/console_libraries"

    - name: Copy Prometheus Config File
      ansible.builtin.copy:
        src: ../config/prometheus/prometheus.yml
        dest: "{{ config_dir }}"

    - name: Create Prometheus Service
      ansible.builtin.copy:
        src: ../config/systemd/prometheus.service
        dest: /etc/systemd/system

    - name: Daemon Reload
      ansible.builtin.systemd:
        name: prometheus
        state: reloaded

    - name: Start Prometheus Service
      ansible.builtin.systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Clean Temporary Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        force: yes
      with_items:
        - "{{ temp_dir }}/prometheus-2.48.0.linux-amd64"
        - "{{ temp_dir }}/{{ packages.package_name }}"
