- hosts: all
  become: true
  tasks:
    - name: Update YUM cache
      yum:
        name: '*'
        state: latest

    - name: Install qemu-guest-agent package
      yum:
        name: qemu-guest-agent
        state: present

    - name: Reboot machine
      command: reboot
      async: 0
      poll: 0
      ignore_errors: yes

    - name: Wait for machine to come back online
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300
